### ISSUE TITLE
Let benchmarks perform multiple runs internally

### ISSUE THREAD

**Issue by athas** [bh107/benchpress#9]
I'd like to try out Benchpress, but for my purposes it's awkward (=slow) to start up each benchmark several times.  I'd much rather Benchpress just ask it to run N times, and get N measurements back.  Would this be a feasible extension?

**Comment by madsbk** [comment]
Fixed in e684a4d582eb2442c277bdcc5b674735a9fb2930, which make all visualizers use all matches of ``--parse-regex``.
The commands within your suite file can then run each benchmark multiple times.
